In [7]:
import pandas as pd

In [8]:
url = "https://klasyfikacje.stat.gov.pl/static/pkd_25/pdf/Wyjasnienia_PKD_2025.xls"
url_codes = "https://klasyfikacje.stat.gov.pl/static/pkd_25/pdf/StrukturaPKD2025.xls"
data = pd.read_excel(url, header=None, names=["code", "desc"])
codes = pd.read_excel(url_codes, names=["-", "-", "-", "code", "desc"], usecols=["code", "desc"])

In [9]:
codes.head()

       code                                               desc
0  Podklasa                                   Nazwa grupowania
1       NaN                                                NaN
2       NaN  Uprawy rolne, chów i hodowla zwierząt, łowiect...
3       NaN                  Uprawy rolne inne niż wieloletnie
4   01.11.Z  Uprawa zbóż innych niż ryż, roślin strączkowyc...

In [10]:
codes.dropna(inplace=True)
codes.drop(0, axis=0, inplace=True)
codes = codes.reset_index(drop=True)

In [11]:
codes.code.unique().shape

(728,)

In [12]:
data.head()

       code                                               desc
0  SEKCJA A                    ROLNICTWO, LEŚNICTWO I RYBACTWO
1       NaN  Sekcja ta obejmuje działalności związane z:\n-...
2  DZIAŁ 01  Uprawy rolne, chów i hodowla zwierząt, łowiect...
3       NaN  Dział ten obejmuje:\n- uprawę i hodowlę roślin...
4      01.1                  Uprawy rolne inne niż wieloletnie

In [13]:
sum(data.code.str.contains(".Z", regex=False) == True)

602

In [14]:
df = pd.read_excel(url, header=None, names=["code", "desc"])
df['group'] = df['code'].notna().cumsum()

df = df.groupby('group').agg({
    'code': 'first',
    'desc': lambda x: ' '.join(x.dropna().astype(str))
}).reset_index(drop=True)

df = df.dropna(subset=['code'])
df['desc'] = df['desc'].str.replace(r'\s+', ' ', regex=True).str.strip()

df.head(10)

       code                                               desc
0  SEKCJA A  ROLNICTWO, LEŚNICTWO I RYBACTWO Sekcja ta obej...
1  DZIAŁ 01  Uprawy rolne, chów i hodowla zwierząt, łowiect...
2      01.1  Uprawy rolne inne niż wieloletnie Grupa ta obe...
3   01.11.Z  Uprawa zbóż innych niż ryż, roślin strączkowyc...
4   01.12.Z   Uprawa ryżu Podklasa ta obejmuje: - uprawę ryżu.
5   01.13.Z  Uprawa warzyw, włączając melony oraz uprawa ro...
6   01.14.Z  Uprawa trzciny cukrowej Podklasa ta nie obejmu...
7   01.15.Z  Uprawa tytoniu Podklasa ta obejmuje: - uprawę ...
8   01.16.Z  Uprawa roślin włóknistych Podklasa ta obejmuje...
9   01.19.Z  Pozostałe uprawy rolne inne niż wieloletnie Po...

In [15]:
df.shape

(1125, 2)

In [16]:
df.code = df.code[df.code.str.contains(".Z", regex=False)]
df = df.dropna(subset=["code"])
df.shape

(602, 2)

In [17]:
df.head()

      code                                               desc
3  01.11.Z  Uprawa zbóż innych niż ryż, roślin strączkowyc...
4  01.12.Z   Uprawa ryżu Podklasa ta obejmuje: - uprawę ryżu.
5  01.13.Z  Uprawa warzyw, włączając melony oraz uprawa ro...
6  01.14.Z  Uprawa trzciny cukrowej Podklasa ta nie obejmu...
7  01.15.Z  Uprawa tytoniu Podklasa ta obejmuje: - uprawę ...

In [18]:
missing_codes = [c for c in codes.code.unique() if c not in df.code.unique()]

In [19]:
len(missing_codes) + df.shape[0]

728

In [20]:
codes

        code                                               desc
0    01.11.Z  Uprawa zbóż innych niż ryż, roślin strączkowyc...
1    01.12.Z                                        Uprawa ryżu
2    01.13.Z  Uprawa warzyw, włączając melony oraz uprawa ro...
3    01.14.Z                            Uprawa trzciny cukrowej
4    01.15.Z                                     Uprawa tytoniu
..       ...                                                ...
723  96.99.Z  Pozostała działalność usługowa, gdzie indziej ...
724  97.00.Z      Gospodarstwa domowe zatrudniające pracowników
725  98.10.Z  Gospodarstwa domowe produkujące wyroby na włas...
726  98.20.Z  Gospodarstwa domowe świadczące usługi na własn...
727  99.00.Z              Organizacje i zespoły eksterytorialne

[728 rows x 2 columns]

In [ ]:
data =

In [25]:
data.isna().sum()

code    0
desc    0
dtype: int64

In [27]:
data.duplicated().sum()

np.int64(0)

In [32]:
data.dtypes

code    object
desc    object
dtype: object

In [61]:
data[data.code.isin(["85.59.CD"])]

Empty DataFrame
Columns: [code, desc]
Index: []

In [2]:
from langchain_community.document_loaders import DataFrameLoader


class PKDDataImporter:
    def __init__(self):
        self.url = "https://klasyfikacje.stat.gov.pl/static/pkd_25/pdf/Wyjasnienia_PKD_2025.xls"
        self._df = None

    def _get_frame(self):
        if self._df is None:
            self._df = pd.read_excel(self.url, header=None, names=["code", "desc"])
        return self._df.copy()

    def _prepare_frame(self):
        df = self._get_frame()
        
        df['group'] = df['code'].notna().cumsum()
        df = df.groupby('group').agg({
            'code': 'first',
            'desc': lambda x: ' '.join(x.dropna().astype(str))
        }).reset_index(drop=True)
        df['desc'] = df['desc'].str.replace(r'\s+', ' ', regex=True).str.strip()
        df = df[df['code'].astype(str).str.contains(r'\.Z', na=False)]
        
        return df 

    def get_loaders(self):
        df = self._prepare_frame()
        loaders = DataFrameLoader(df, page_content_column="desc")
        return loaders.load()

/opt/python/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
importer = PKDDataImporter()
loaders = importer.get_loaders()

In [4]:
loaders[0]

Document(metadata={'code': '01.11.Z'}, page_content='Uprawa zbóż innych niż ryż, roślin strączkowych i roślin oleistych na nasiona Podklasa ta obejmuje uprawę zbóż, roślin strączkowych i roślin oleistych. Ponadto obejmuje uprawę tych roślin do celów produkcji nasion. Uprawa tych zbóż jest często łączona w obrębie gospodarstwa rolnego. Podklasa ta obejmuje: - uprawę zbóż, na przykład: • pszenicy, • kukurydzy innej niż pastewnej, • sorgo, • jęczmienia, • żyta, • owsa, • prosa, • pseudozbóż, to jest owoców lub nasion, wykorzystywanych podobnie jak zboża tradycyjne, na przykład: - komosy ryżowej, - amarantusa, - chia, - uprawę roślin strączkowych, na przykład: • fasoli, • bobu, • ciecierzycy, • wspięgi chińskiej, • soczewicy, • łubinu innego niż pastewny, • grochu, • nikli indyjskiej, - uprawę roślin oleistych na nasiona, na przykład: • soi, • orzeszków ziemnych, • rącznika pospolitego, • siemienia lnianego, • gorczycy, • bawełny, • rzepaku, • szafranu, • sezamu, • słonecznika. Podklasa ta nie obejmuje: - uprawy ryżu, sklasyfikowanej w 01.12.Z, - uprawy kukurydzy cukrowej, sklasyfikowanej w 01.13.Z, - uprawy roślin pastewnych: kukurydzy, łubinu lub jarmużu, sklasyfikowanej w 01.19.Z, - uprawy drzew oleistych na owoce, sklasyfikowanej w 01.26.Z.')

In [ ]:
documents = []

TypeError: 'Document' object is not subscriptable

'Uprawa zbóż innych niż ryż, roślin strączkowych i roślin oleistych na nasiona Podklasa ta obejmuje uprawę zbóż, roślin strączkowych i roślin oleistych. Ponadto obejmuje uprawę tych roślin do celów produkcji nasion. Uprawa tych zbóż jest często łączona w obrębie gospodarstwa rolnego. Podklasa ta obejmuje: - uprawę zbóż, na przykład: • pszenicy, • kukurydzy innej niż pastewnej, • sorgo, • jęczmienia, • żyta, • owsa, • prosa, • pseudozbóż, to jest owoców lub nasion, wykorzystywanych podobnie jak zboża tradycyjne, na przykład: - komosy ryżowej, - amarantusa, - chia, - uprawę roślin strączkowych, na przykład: • fasoli, • bobu, • ciecierzycy, • wspięgi chińskiej, • soczewicy, • łubinu innego niż pastewny, • grochu, • nikli indyjskiej, - uprawę roślin oleistych na nasiona, na przykład: • soi, • orzeszków ziemnych, • rącznika pospolitego, • siemienia lnianego, • gorczycy, • bawełny, • rzepaku, • szafranu, • sezamu, • słonecznika. Podklasa ta nie obejmuje: - uprawy ryżu, sklasyfikowanej w 01.12.Z, - uprawy kukurydzy cukrowej, sklasyfikowanej w 01.13.Z, - uprawy roślin pastewnych: kukurydzy, łubinu lub jarmużu, sklasyfikowanej w 01.19.Z, - uprawy drzew oleistych na owoce, sklasyfikowanej w 01.26.Z.'

In [54]:
loaders

[Document(metadata={'code': '01.11.Z'}, page_content='Uprawa zbóż innych niż ryż, roślin strączkowych i roślin oleistych na nasiona Podklasa ta obejmuje uprawę zbóż, roślin strączkowych i roślin oleistych. Ponadto obejmuje uprawę tych roślin do celów produkcji nasion. Uprawa tych zbóż jest często łączona w obrębie gospodarstwa rolnego. Podklasa ta obejmuje: - uprawę zbóż, na przykład: • pszenicy, • kukurydzy innej niż pastewnej, • sorgo, • jęczmienia, • żyta, • owsa, • prosa, • pseudozbóż, to jest owoców lub nasion, wykorzystywanych podobnie jak zboża tradycyjne, na przykład: - komosy ryżowej, - amarantusa, - chia, - uprawę roślin strączkowych, na przykład: • fasoli, • bobu, • ciecierzycy, • wspięgi chińskiej, • soczewicy, • łubinu innego niż pastewny, • grochu, • nikli indyjskiej, - uprawę roślin oleistych na nasiona, na przykład: • soi, • orzeszków ziemnych, • rącznika pospolitego, • siemienia lnianego, • gorczycy, • bawełny, • rzepaku, • szafranu, • sezamu, • słonecznika. Podklasa ta nie obejmuje: - uprawy ryżu, sklasyfikowanej w 01.12.Z, - uprawy kukurydzy cukrowej, sklasyfikowanej w 01.13.Z, - uprawy roślin pastewnych: kukurydzy, łubinu lub jarmużu, sklasyfikowanej w 01.19.Z, - uprawy drzew oleistych na owoce, sklasyfikowanej w 01.26.Z.'),
 Document(metadata={'code': '01.12.Z'}, page_content='Uprawa ryżu Podklasa ta obejmuje: - uprawę ryżu.'),
 Document(metadata={'code': '01.13.Z'}, page_content='Uprawa warzyw, włączając melony oraz uprawa roślin korzeniowych i roślin bulwiastych Podklasa ta obejmuje: - uprawę warzyw kwiatostanowych, liściowych i łodygowych, na przykład: • karczochów, • szparagów, • kapusty, • kalafiora i brokułów, • sałaty i cykorii, • szpinaku, - uprawę warzyw owocowych, na przykład: • ogórków, w tym korniszonów, • bakłażanów (oberżyn), • pomidorów, • arbuzów, • kantalup, • melonów, - uprawę warzyw korzeniowych, cebulowych i bulwiastych, na przykład: • marchwi, • rzepy, • czosnku, • cebuli, w tym szalotki, • pora i pozostałych warzyw cebulowych, - uprawę grzybów, w tym trufli, - uprawę buraków cukrowych, - uprawę kukurydzy cukrowej, - uprawę chili i papryki słodkiej (z rodzaju Capsicum), - produkcję nasion warzyw, w tym nasion buraka cukrowego, - uprawę roślin korzeniowych i bulwiastych, na przykład: • ziemniaków, • słodkich ziemniaków (patatów, batatów), • manioków, • pochrzynu (ignamu), • brukwi i buraka liściowego (boćwiny). Podklasa ta nie obejmuje: - produkcji nasion buraka pastewnego, sklasyfikowanej w 01.19.Z, - uprawy roślin przyprawowych i aromatycznych oraz roślin wykorzystywanych do produkcji leków i wyrobów farmaceutycznych, sklasyfikowanej w 01.28.Z, - uprawy grzybni, sklasyfikowanej w 01.30.Z.'),
 Document(metadata={'code': '01.14.Z'}, page_content='Uprawa trzciny cukrowej Podklasa ta nie obejmuje: - uprawy buraka cukrowego, sklasyfikowanej w 01.13.Z.'),
 Document(metadata={'code': '01.15.Z'}, page_content='Uprawa tytoniu Podklasa ta obejmuje: - uprawę tytoniu, - wstępną obróbkę tytoniu związaną z jego uprawą. Podklasa ta nie obejmuje: - przygotowywania liści tytoniu (na przykład suszenia w warunkach naturalnych) wykonywanego na zlecenie, sklasyfikowanego w 01.63.Z, - produkcji wyrobów tytoniowych, sklasyfikowanej w 12.00.Z.'),
 Document(metadata={'code': '01.16.Z'}, page_content='Uprawa roślin włóknistych Podklasa ta obejmuje uprawę roślin włóknistych, na przykład: - bawełny, - juty, ketmii konopiowatej i pozostałych roślin na włókna łykowe, - lnu i konopi, - sizalu i pozostałych roślin z rodziny agawy na włókna tekstylne, - konopi manilskich, ramii i pozostałych roślin na włókna tekstylne. Podklasa ta obejmuje również roszenie uprawianych roślin włóknistych przeprowadzane w warunkach naturalnych. Podklasa ta nie obejmuje: - roszenia roślin włóknistych świadczonego na zlecenie, sklasyfikowanego w 01.63.Z.'),
 Document(metadata={'code': '01.19.Z'}, page_content='Pozostałe uprawy rolne inne niż wieloletnie Podklasa ta obejmuje pozostałe uprawy rolne inne niż wieloletnie, na przykład: - uprawę koniczyny, lucerny (alfalfa), esparcety, kukurydzy pastewnej, łubinu pastewnego i pozostałych traw innych niż rośliny wieloletnie, kapusty pastewnej i podobnych roślin pastewnych, - produkcję nasion buraka pastewnego, - produkcję nasion pozostałych roślin pastewnych, - uprawę kwiatów, w tym kwiatów ciętych i pączków kwiatowych, - produkcję nasion kwiatów. Podklasa ta obejmuje również: - uprawę kwiatów wieloletnich i innych roślin ozdobnych. Podklasa ta nie obejmuje: - produkcji nasion buraka cukrowego, sklasyfikowanej w 01.13.Z, - uprawy roślin przyprawowych i aromatycznych, roślin wykorzystywanych do produkcji leków i wyrobów farmaceutycznych, innych niż rośliny wieloletnie, sklasyfikowanej w 01.28.Z.'),
 Document(metadata={'code': '01.21.Z'}, page_content='Uprawa winogron Podklasa ta obejmuje: - uprawę winogron do konsumpcji lub do dalszej produkcji na wino, soki, ocet i suszone owoce, na przykład na rodzynki, w tym rodzynki koryntki lub rodzynki sułtańskie. Podklasa ta nie obejmuje: - produkcji soków, sklasyfikowanej w 10.32.Z, - produkcji wina, sklasyfikowanej w 11.02.Z.'),
 Document(metadata={'code': '01.22.Z'}, page_content='Uprawa drzew i krzewów owocowych tropikalnych i podzwrotnikowych Podklasa ta obejmuje uprawę drzew i krzewów owocowych tropikalnych i podzwrotnikowych, na przykład: - awokado, - bananów i platanów, - daktyli, - fig, - mango, - papai, - ananasów, - rambutanów, - liczi.'),
 Document(metadata={'code': '01.23.Z'}, page_content='Uprawa drzew i krzewów owocowych cytrusowych Podklasa ta obejmuje uprawę drzew i krzewów owocowych cytrusowych, na przykład: - grejpfrutów i pomelo, - cytryn i limonek, - pomarańczy, - tangerynek, mandarynek i klementynek.'),
 Document(metadata={'code': '01.24.Z'}, page_content='Uprawa drzew i krzewów owocowych ziarnkowych i pestkowych Podklasa ta obejmuje uprawę drzew i krzewów owocowych ziarnkowych i pestkowych, na przykład: - jabłek, - moreli, - czereśni i wiśni, - brzoskwiń i nektarynek, - gruszek i pigw, - śliwek i tarnin. Podklasa ta nie obejmuje: - uprawy mango, rambutanów i liczi, sklasyfikowanej w 01.22.Z, - uprawy oliwek, sklasyfikowanej w 01.26.Z.'),
 Document(metadata={'code': '01.25.Z'}, page_content='Uprawa pozostałych drzew i krzewów owocowych oraz orzechowych Podklasa ta obejmuje: - uprawę drzew i krzewów owocowych jagodowych, na przykład: • czarnej borówki, • porzeczki, • agrestu, • owoców kiwi, • malin, • truskawek, • rokitnika, - produkcję nasion owoców, - uprawę orzechów jadalnych: • migdałów, • orzechów nerkowca, • kasztanów jadalnych, • orzechów laskowych, • orzeszków pistacjowych, • orzechów włoskich, • orzeszków piniowych, - uprawę pozostałych drzew i krzewów owocowych, na przykład: • chleba świętojańskiego. Podklasa ta nie obejmuje: - uprawy orzechów kokosowych, sklasyfikowanej w 01.26.Z.'),
 Document(metadata={'code': '01.26.Z'}, page_content='Uprawa drzew oleistych Podklasa ta obejmuje uprawę drzew oleistych na owoce, na przykład: - orzechów kokosowych, - oliwek, - olejowców. Podklasa ta nie obejmuje: - produkcji nasion soi, nasion orzechów ziemnych i pozostałych nasion oleistych, sklasyfikowanej w 01.11.Z, - uprawy orzechów na olej (na przykład orzechów włoskich, migdałów, orzechów laskowych, orzeszków piniowych lub orzeszków pistacjowych), sklasyfikowanej w 01.25.Z.'),
 Document(metadata={'code': '01.27.Z'}, page_content='Uprawa roślin wykorzystywanych do produkcji napojów Podklasa ta obejmuje uprawę roślin wykorzystywanych do produkcji napojów, na przykład: - kawy, - herbaty, - maté (herbaty paragwajskiej), - kakao. Podklasa ta nie obejmuje: - uprawy winogron, sklasyfikowanej w 01.21.Z, - uprawy chmielu, sklasyfikowanej w 01.28.Z.'),
 Document(metadata={'code': '01.28.Z'}, page_content='Uprawa roślin przyprawowych i aromatycznych oraz roślin wykorzystywanych do produkcji leków i wyrobów farmaceutycznych Podklasa ta obejmuje: - uprawę roślin przyprawowych i aromatycznych, wieloletnich i innych niż wieloletnie: • pieprzu (z rodzaju Piper), • gałki muszkatołowej, kwiatu muszkatołowego i kardamonu, • anyżu, badianu i kopru włoskiego, przyprawowych lub aromatycznych, • cynamonu, • goździków, • imbiru, • wanilii, • chmielu, • kminku, - uprawę roślin wykorzystywanych do produkcji leków, środków odurzających i wyrobów farmaceutycznych, - suszenie w warunkach naturalnych roślin przyprawowych i aromatycznych, roślin wykorzystywanych do produkcji leków i wyrobów farmaceutycznych, związane z uprawą tych roślin. Podklasa ta nie obejmuje: - suszenia roślin przyprawowych i aromatycznych, roślin wykorzystywanych do produkcji leków i wyrobów farmaceutycznych, wykonywanego na zlecenie, sklasyfikowanego w 01.63.Z.'),
 Document(metadata={'code': '01.29.Z'}, page_content='Uprawa pozostałych roślin wieloletnich Podklasa ta obejmuje: - uprawę drzew kauczukowych w celu zbierania mleczka kauczukowego (lateksu), - uprawę choinek świątecznych, - uprawę drzew w celu uzyskania soków, - uprawę roślin wieloletnich używanych do wyplatania. Podklasa nie obejmuje: - uprawy kwiatów, w tym kwiatów ciętych i pączków kwiatowych, sklasyfikowanej w 01.19.Z, - zbierania soków lub żywic gumopodobnych z drzew dziko rosnących, sklasyfikowanego w 02.30.Z.'),
 Document(metadata={'code': '01.30.Z'}, page_content='Rozmnażanie roślin Podklasa ta obejmuje produkcję roślinnych materiałów wegetatywnych, w tym sadzonek, odrostów i rozsad przeznaczonych do bezpośredniego rozmnażania roślin lub gromadzenia szczepów roślinnych, do których zaszczepiany jest wybrany szczep, do ewentualnego obsadzania upraw. Podklasa ta obejmuje: - uprawę roślin do rozmnażania, - uprawę roślin ozdobnych, w tym darni do przesadzania, - uprawę roślin dla cebulek, bulw i korzeni; sadzonki i szczepy, - uprawę grzybni, w tym podłoża z wsianą grzybnią, - uprawę szkółkarską, z wyłączeniem szkółek leśnych. Podklasa ta nie obejmuje: - uprawy roślin do produkcji nasion, sklasyfikowanej w odpowiednich podklasach grup 01.1 i 01.2, - działalności szkółek leśnych, sklasyfikowanej w 02.10.Z, - produkcji podłoża bez wsianej grzybni, sklasyfikowanej w 20.15.Z.'),
 Document(metadata={'code': '01.41.Z'}, page_content='Chów i hodowla bydła mlecznego Podklasa ta obejmuje: - chów i hodowlę bydła i bawołów ras mlecznych, - produkcję surowego mleka krowiego lub bawolego, - produkcję nasienia bydlęcego i bawolego ras mlecznych. Podklasa ta nie obejmuje: - przetwórstwa mleka, sklasyfikowanego w 10.51.Z.'),
 Document(metadata={'code': '01.42.Z'}, page_content='Chów i hodowla pozostałego bydła i bawołów Podklasa ta obejmuje: - chów i hodowlę bydła i bawołów na mięso, - produkcję nasienia bydlęcego i bawolego ras innych niż mleczne, - chów i hodowlę bydła i bawołów pociągowych, - chów i hodowlę byków bojowych.'),
 Document(metadata={'code': '01.43.Z'}, page_content='Chów i hodowla koni i pozostałych zwierząt koniowatych Podklasa ta obejmuje: - chów i hodowlę koni, osłów, mułów lub osłomułów, bez względu na ich przeznaczenie, - produkcję nasienia ogierów. Podklasa ta nie obejmuje: - działalności stajni koni wyścigowych i jeździeckich, nieprowadzących działalności hodowlanej, sklasyfikowanej w 93.19.Z.'),
 Document(metadata={'code': '01.44.Z'}, page_content='Chów i hodowla wielbłądów i zwierząt wielbłądowatych Podklasa ta obejmuje: - chów i hodowlę wielbłądów (dromaderów) i zwierząt wielbłądowatych, - produkcję nasienia wielbłądów.'),
 Document(metadata={'code': '01.45.Z'}, page_content='Chów i hodowla owiec i kóz Podklasa ta obejmuje: - chów i hodowlę owiec i kóz, - produkcję surowego mleka owczego i koziego, - produkcję surowej wełny, - produkcję nasienia kozłów i tryków. Podklasa ta nie obejmuje: - strzyżenia owiec, wykonywanego na zlecenie, sklasyfikowanego w 01.62.Z, - produkcji wełny surowej poubojowej, sklasyfikowanej w 10.11.Z, - przetwórstwa mleka, sklasyfikowanego w 10.51.Z.'),
 Document(metadata={'code': '01.46.Z'}, page_content='Chów i hodowla świń Podklasa ta obejmuje: - chów i hodowlę świń, - produkcję nasienia knurów.'),
 Document(metadata={'code': '01.47.Z'}, page_content='Chów i hodowla drobiu Podklasa ta obejmuje: - chów i hodowlę drobiu, na przykład: • kurczaków, indyków, kaczek, gęsi, przepiórek, strusi, perliczek, - produkcję jaj drobiowych, - działalność wylęgarni drobiu. Podklasa ta nie obejmuje: - produkcji pierza i puchu, sklasyfikowanej w 10.12.Z.'),
 Document(metadata={'code': '01.48.Z'}, page_content='Chów i hodowla pozostałych zwierząt Podklasa ta obejmuje: - chów i hodowlę pozostałych zwierząt, w tym częściowo udomowionych, na przykład: • ptaków (z wyłączeniem drobiu i strusi), • owadów, • królików i pozostałych zwierząt futerkowych, • reniferów, - pozyskiwanie skór surowych z pozostałych zwierząt, w tym z ptaków lub gadów, na przykład węży i żółwi, w gospodarstwach hodowlanych, - chów i hodowlę gadów, z wyłączeniem krokodyli, - chów i hodowlę robaków, mięczaków, w tym ślimaków i tym podobnych zwierząt lądowych, - chów i hodowlę jedwabników; produkcję kokonów jedwabników, - chów i hodowlę pszczół; produkcję produktów pszczelich (na przykład miodu, wosku pszczelego, propolisu, plastrów miodu, jadu pszczelego); rozmnażanie pszczół na sprzedaż, - chów i hodowlę zwierząt domowych (z wyłączeniem ryb), na przykład: • kotów i psów, • ptaków, na przykład papużek, • chomików. Podklasa ta nie obejmuje: - chowu i hodowli drobiu, sklasyfikowanych w 01.47.Z, - chowu i hodowli ryb ozdobnych, sklasyfikowanych w odpowiednich podklasach grupy 03.2, - chowu i hodowli ryb, żab, krokodyli i robaków wodnych, sklasyfikowanych w 03.21.Z, 03.22.Z, - tresury zwierząt domowych, sklasyfikowanej w 96.99.Z, - prowadzenia schronisk dla zwierząt domowych, sklasyfikowanego w 96.99.Z.'),
 Document(metadata={'code': '01.50.Z'}, page_content='Uprawy rolne połączone z chowem i hodowlą zwierząt (działalność mieszana) Podklasa ta obejmuje gospodarstwa rolne prowadzące jednocześnie produkcję roślinną i zwierzęcą, bez specjalizacji produkcji w kierunku upraw rolnych czy też chowu i hodowli zwierząt. Wielkość produkcji rolnej nie jest czynnikiem decydującym. Jeżeli jednak stopień specjalizacji produkcji wynosi 66 % i powyżej w jednej dziedzinie, to działalność podmiotu gospodarczego nie powinna być klasyfikowana w niniejszej podklasie, ale do upraw rolnych lub chowu i hodowli zwierząt. Podklasa ta nie obejmuje: - działalności podmiotów gospodarczych zajmujących się głównie uprawami rolnymi, sklasyfikowanej w odpowiednich podklasach grup 01.1 i 01.2, - działalności podmiotów gospodarczych zajmujących się głównie chowem i hodowlą zwierząt, sklasyfikowanej w odpowiednich podklasach grupy 01.4.'),
 Document(metadata={'code': '01.61.Z'}, page_content='Działalność usługowa wspomagająca produkcję roślinną Podklasa ta obejmuje: - działalność związaną z produkcją roślinną świadczoną na zlecenie, w zakresie: • przygotowania pól do upraw, siewu i sadzenia, • pielęgnowania, zraszania, opryskiwania upraw, w tym usług agrolotniczych, • przycinania drzew owocowych oraz winorośli, • przesadzania ryżu, przerywania buraków, • zbiorów, • zwalczania szkodników (w tym królików) związanego z rolnictwem, - eksploatację systemów irygacyjnych dla celów rolniczych, - wynajem maszyn rolniczych z obsługą, - utrzymanie gruntów własnych lub dzierżawionych w dobrym stanie ekologicznym, wyłączając produkcję rolną. Podklasa ta nie obejmuje: - działalności rolniczej następującej po zbiorach, sklasyfikowanej w 01.63.Z, - odwadniania gruntów rolnych, sklasyfikowanego w 43.12.Z, - działalności w zakresie architektury krajobrazu, sklasyfikowanej w 71.11.Z, - działalności agronomów i ekonomistów rolnych, sklasyfikowanej w 74.99.Z, - zagospodarowania terenów zieleni, sklasyfikowanego w 81.30.Z, - organizowania pokazów i targów rolniczych, sklasyfikowanego w 82.30.Z.'),
 Document(metadata={'code': '01.62.Z'}, page_content='Działalność usługowa wspomagająca chów i hodowlę zwierząt gospodarskich Podklasa ta obejmuje: - działalność związaną z chowem i hodowlą zwierząt gospodarskich, świadczoną na zlecenie, w zakresie: • działalności promujących wzrost produkcji zwierząt gospodarskich, • opieki nad stadem, wypasania cudzego inwentarza, trzebienia kogutów, czyszczenia kojców i tym podobnych, • działalności związanych ze sztucznym unasiennianiem, • kolczykowania zwierząt, • korekty racic, usuwania poroża, obcinania kiełków u prosiąt, kurtyzacji zwierząt gospodarskich (obcinanie ogonków), • przygotowania zwierząt gospodarskich do wystaw i pokazów, • strzyżenia owiec, • prowadzenia schronisk dla zwierząt gospodarskich, - podkuwanie koni. Podklasa ta nie obejmuje: - wynajmu miejsc w schroniskach dla zwierząt gospodarskich, sklasyfikowanego w 68.20.Z, - działalności w zakresie badań naukowych w dziedzinie nauk rolniczych, sklasyfikowanej w 72.10.Z, - działalności weterynaryjnej, w tym szczepienia zwierząt, sklasyfikowanej w 75.00.Z, - wynajmowania zwierząt (na przykład stada zwierząt, koni wyścigowych), sklasyfikowanego w 77.39.Z, - prowadzenia schronisk dla zwierząt domowych, sklasyfikowanego w 96.99.Z.'),
 Document(metadata={'code': '01.63.Z'}, page_content='Działalność usługowa następująca po zbiorach oraz obróbka nasion dla celów rozmnażania roślin Podklasa ta obejmuje działalność usługową następującą po zbiorach, wykonywaną na zlecenie: - przygotowanie plonów do sprzedaży na rynek pierwotny, na przykład poprzez czyszczenie, obcinanie, sortowanie, odkażanie, - odziarnianie bawełny, - przygotowanie liści tytoniowych, szyszek chmielowych, ziół, na przykład suszenie w warunkach naturalnych, - przygotowanie ziaren kakaowych, na przykład łuskanie, - woskowanie owoców, - suszenie owoców, warzyw, ziół, przypraw, ziół leczniczych i tytoniu, - sortowanie, czyszczenie, cięcie i suszenie ziół leczniczych, - suszenie ziarna, - działalność następującą po zbiorach skierowaną na polepszenie jakości nasion, na przykład poprzez usunięcie nasion niewyrośniętych, uszkodzonych, niedojrzałych lub poprzez utrzymywanie wilgotności nasion na poziomie bezpiecznym dla ich przechowywania, - roszenie roślin włóknistych (takich jak juta, len, kokos) niezwiązane z ich uprawą, - zabiegi przyspieszające dojrzewanie owoców, na przykład przyspieszające dojrzewanie bananów, - suszenie, czyszczenie, sortowanie i przechowywanie nasion do momentu ich sprzedaży, - obróbkę nasion genetycznie modyfikowanych. Podklasa ta nie obejmuje: - przygotowania do sprzedaży produktów rolniczych przez producenta, sklasyfikowanego w odpowiednich podklasach grup 01.1, 01.2 i 01.3, - produkcji nasion, sklasyfikowanej w odpowiednich podklasach grup 01.1 i 01.2, - usług związanych z przetwarzaniem nasion w celu otrzymania oleju, sklasyfikowanych w 10.41.Z, - wstępnego przetwarzania surowca tytoniowego, to jest przygotowania do dalszego przerobu przez producentów wyrobów tytoniowych surowca tytoniowego, polegającego w szczególności na odżyłowaniu, cięciu, nasączaniu lub dosuszaniu blaszki liściowej, sklasyfikowanego w 12.00.Z, - działalności marketingowej wykonywanej na zlecenie, sklasyfikowanej w odpowiednich podklasach działu 46, - sprzedaży hurtowej płodów rolnych, sklasyfikowanej w odpowiednich podklasach grupy 46.2, - badań eksperymentalnych związanych z rozwojem i modyfikacją nasion, sklasyfikowanych w 72.10.Z.'),

In [28]:
df = importer._get_frame()

In [3]:
df = pd.read_excel("https://klasyfikacje.stat.gov.pl/static/pkd_25/pdf/Wyjasnienia_PKD_2025.xls", header=None, names=["code", "desc"])

In [4]:
df.head()

       code                                               desc
0  SEKCJA A                    ROLNICTWO, LEŚNICTWO I RYBACTWO
1       NaN  Sekcja ta obejmuje działalności związane z:\n-...
2  DZIAŁ 01  Uprawy rolne, chów i hodowla zwierząt, łowiect...
3       NaN  Dział ten obejmuje:\n- uprawę i hodowlę roślin...
4      01.1                  Uprawy rolne inne niż wieloletnie

In [24]:
df = importer._prepare_frame()

In [25]:
df.head()

      code                                               desc
3  01.11.Z  Uprawa zbóż innych niż ryż, roślin strączkowyc...
4  01.12.Z   Uprawa ryżu Podklasa ta obejmuje: - uprawę ryżu.
5  01.13.Z  Uprawa warzyw, włączając melony oraz uprawa ro...
6  01.14.Z  Uprawa trzciny cukrowej Podklasa ta nie obejmu...
7  01.15.Z  Uprawa tytoniu Podklasa ta obejmuje: - uprawę ...

In [26]:
df.shape

(602, 2)

In [17]:
len(loaders.load())

602

In [5]:
from langchain_community.document_loaders import DataFrameLoader

/opt/python/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [20]:
loader = DataFrameLoader(cleaned_df, page_content_column="desc")

In [19]:
cleaned_df.isna().sum()

code    0
desc    0
dtype: int64

In [27]:
loader.load()[3]

Document(metadata={'code': '01.11.Z'}, page_content='Uprawa zbóż innych niż ryż, roślin strączkowych i roślin oleistych na nasiona Podklasa ta obejmuje uprawę zbóż, roślin strączkowych i roślin oleistych. Ponadto obejmuje uprawę tych roślin do celów produkcji nasion. Uprawa tych zbóż jest często łączona w obrębie gospodarstwa rolnego. Podklasa ta obejmuje: - uprawę zbóż, na przykład: • pszenicy, • kukurydzy innej niż pastewnej, • sorgo, • jęczmienia, • żyta, • owsa, • prosa, • pseudozbóż, to jest owoców lub nasion, wykorzystywanych podobnie jak zboża tradycyjne, na przykład: - komosy ryżowej, - amarantusa, - chia, - uprawę roślin strączkowych, na przykład: • fasoli, • bobu, • ciecierzycy, • wspięgi chińskiej, • soczewicy, • łubinu innego niż pastewny, • grochu, • nikli indyjskiej, - uprawę roślin oleistych na nasiona, na przykład: • soi, • orzeszków ziemnych, • rącznika pospolitego, • siemienia lnianego, • gorczycy, • bawełny, • rzepaku, • szafranu, • sezamu, • słonecznika. Podklasa ta nie obejmuje: - uprawy ryżu, sklasyfikowanej w 01.12.Z, - uprawy kukurydzy cukrowej, sklasyfikowanej w 01.13.Z, - uprawy roślin pastewnych: kukurydzy, łubinu lub jarmużu, sklasyfikowanej w 01.19.Z, - uprawy drzew oleistych na owoce, sklasyfikowanej w 01.26.Z.')